#!/bin/bash
genome=`realpath $1`
threads=$2
exist_lib=$3
if [ ! -e "$exist_lib" ];then
	exist_lib=none
else
	exist_lib=`realpath $3`
fi
wkdir=$PWD
bin_dir=`realpath $0|xargs -n1 dirname`
cleanup_misclas=$bin_dir/scripts/software/EDTA-2.2.2/bin/cleanup_misclas.pl
cleanup_tandem=$bin_dir/scripts/software/EDTA-2.2.2/bin/cleanup_tandem.pl
output_by_list=$bin_dir/scripts/software/EDTA-2.2.2/bin/output_by_list.pl
teclass_images="teclass-2.1.3b:latest"

echo -e "\033[01;35m#######Data#######\033[0m"
echo "Genome: $genome
Threads: $threads
Exist Library: $exist_lib"

echo -e "\n\033[01;35m#######Run#######\033[0m"
mkdir -p tmp_of_EDTA-RepeatModeler2;cd tmp_of_EDTA-RepeatModeler2;now_dir=$PWD
mkdir -p 01.repeatmodeler2;cd 01.repeatmodeler2
echo "1.1. BuildDatabase -name mydb `basename $genome` ..."
if [ "$exist_lib" == "none" ];then
	if [ ! -e run_01build_DB.sh.done ];then
		echo "BuildDatabase -name mydb ${genome} && touch run_01build_DB.sh.done" >run_01build_DB.sh
		bash run_01build_DB.sh 1>run_01build_DB.sh.log 2>run_01build_DB.sh.err
	fi
	if [ `cat run_01build_DB.sh.err|wc -l` != "0" ];then rm -rf run_01build_DB.sh.done;fi
	if [ ! -e run_01build_DB.sh.done ];then echo -e "BuildDatabase failed" && exit 1;fi

	echo "1.2. RepeatModeler2 denovo discover repeat ..."
	if [ ! -e run_02denovo.sh.done ];then
		echo "RM2_dir=\`ls|grep \"^RM_*\"|head -n1|sed 's/^$/none/g'\`
#if [ -e \"\$RM2_dir\" ];then
#	RepeatModeler -recoverDir ./\$RM2_dir -database mydb -quick -threads $threads && touch run_02denovo.sh.done
#else
RepeatModeler -database mydb -quick -threads $threads && touch run_02denovo.sh.done
#fi" >run_02denovo.sh
		bash run_02denovo.sh 1>run_02denovo.sh.log 2>run_02denovo.sh.err
	fi
	#if [ `cat run_02denovo.sh.err|wc -l` != "0" ];then rm -rf run_02denovo.sh.done;fi
	if [ ! -s mydb-families.fa ];then rm -rf run_02denovo.sh.done;fi
	if [ ! -e run_02denovo.sh.done ];then echo "RepeatModeler2 De-Novo Discover Repeat faied" && exit 1;fi
else
	ln -sf $exist_lib ./mydb-families.fa
fi

mkdir -p ../02.classify;cd ../02.classify
echo "2.1. Annotate and remove misclassified candidates ..."
if [ ! -e run_01first_class.sh.done ];then
	echo "#!/bin/bash
	cat ../01.repeatmodeler2/mydb-families.fa|sed 's/ .*$//g'|sed 's/Unknown/unknown/g'|seqkit seq -u -w0 >genome.RM2.raw.fa.tmp && \\
cat genome.RM2.raw.fa.tmp|seqkit seq -n|grep -E \"#DNA|#LTR|#LINE|#SINE|nknown\"|seqtk subseq genome.RM2.raw.fa.tmp - >genome.RM2.raw.fa && \\
mkdir -p fisrt_TEsorter && cd fisrt_TEsorter && ln -sf ../genome.RM2.raw.fa && \\
TEsorter genome.RM2.raw.fa --disable-pass2 -p $threads 2>/dev/null && \\
perl $cleanup_misclas genome.RM2.raw.fa.rexdb.cls.tsv
cat genome.RM2.raw.fa.rexdb.cls.tsv|grep '#unknown'|sed '/mixture\\tmixture\\t/d'|grep 'mixture'|sed 's#mixture#unknown#g'|cut -f1-3|sed 's/#/\\t/g'|awk '{print \$1\"#\"\$2\"\\t\"\$1\"#\"\$3\"/\"\$4}'|sed 's#\\t#$%>#g'|sed 's#\$#%g#g'|sed 's#^#s%>#g' >sed_file && \\
sed -f sed_file genome.RM2.raw.fa.cln >genome.RM2.raw.fa.cln1 && \\
chmod +x genome.RM2.raw.fa.cln1 && \\
touch ../run_01first_class.sh.done" >run_01first_class.sh
	bash run_01first_class.sh 1>run_01first_class.sh.log 2>run_01first_class.sh.err
fi
#if [ `cat run_01first_class.sh.err|wc -l` != "0" ];then rm -rf run_01first_class.sh.done;fi
if [ ! -s fisrt_TEsorter/genome.RM2.raw.fa.cln1 ];then rm -rf run_01first_class.sh.done;fi
if [ ! -e run_01first_class.sh.done ];then echo -e "Annotate and remove misclassified candidates failed" && exit 1;fi
echo "2.2. Reclassify clean candidates ..."
if [ ! -e run_02second_class.sh.done ];then
	echo "mkdir -p second_TEsorter;cd second_TEsorter && \\
ln -sf ../fisrt_TEsorter/genome.RM2.raw.fa.cln1 ./ && \\
TEsorter genome.RM2.raw.fa.cln1 --disable-pass2 -p $threads 2>/dev/null && \\
perl -nle 's/>\\S+\\s+/>/; print \$_' genome.RM2.raw.fa.cln1.rexdb.cls.lib >genome.RM2.raw.fa.cln2 && rm -rf TE_Unknown.lib_* && \\
ln -sf genome.RM2.raw.fa.cln2 genome.RM2.raw.fa.cln3 && \\
touch ../run_02second_class.sh.done" >run_02second_class.sh
	bash run_02second_class.sh 1>run_02second_class.sh.log 2>run_02second_class.sh.err
fi
#if [ ! -s second_TEsorter/TEclass_result.lib.fa ];then rm -rf run_02second_class.sh.done;fi
if [ ! -e run_02second_class.sh.done ];then echo -e "Reclassify clean candidates failed" && exit 1;fi
echo "2.3. Clean up tandem repeat ..."
if [ ! -e run_03remove_TR.sh.done ];then
	echo "perl $cleanup_tandem -misschar N -nc 50000 -nr 0.8 -minlen 80 -minscore 3000 -trf 1 -cleanN 1 -cleanT 1 -f second_TEsorter/genome.RM2.raw.fa.cln3 >genome.RM2.raw.fa.cln4 && \\
grep -P 'LINE' genome.RM2.raw.fa.cln4 | perl $output_by_list 1 genome.RM2.raw.fa.cln4 1 - -FA >genome.LINE.raw.fa && \\
grep -P 'SINE' genome.RM2.raw.fa.cln4 | perl $output_by_list 1 genome.RM2.raw.fa.cln4 1 - -FA >genome.SINE.raw.fa && \\
grep -P 'LINE|SINE' genome.RM2.raw.fa.cln4 | perl $output_by_list 1 genome.RM2.raw.fa.cln4 1 - -FA >genome.LINE_SINE.raw.fa && \\
grep -P 'LINE|SINE|RNA' genome.RM2.raw.fa.cln4 | perl $output_by_list 1 genome.RM2.raw.fa.cln4 1 - -FA -ex >genome.RM2.without_LINE_SINE.fa && \\
cat genome.RM2.without_LINE_SINE.fa genome.LINE.raw.fa >genome.RM2.all.fa && \\
seqkit fx2tab -inl genome.RM2.all.fa >genome.RM2.all.fa.len && \\
echo -e \"Type\\tCount\\n\`cat genome.RM2.all.fa.len|sed 's/#/\\t/g'|cut -f2|sed 's#RC/Helitron#Helitron#g'|sed 's#/#\\t#g'|cut -f1|sort|uniq -c|awk '{print \$2\"\\t\"\$1}'\`\"|column -t >stat.txt && \\
chmod +x genome.RM2.all.fa genome.RM2.without_LINE_SINE.fa genome.LINE.raw.fa && touch run_03remove_TR.sh.done" >run_03remove_TR.sh
	bash run_03remove_TR.sh 1>run_03remove_TR.sh.log 2>run_03remove_TR.sh.err
fi
if [ `cat run_03remove_TR.sh.err|wc -l` != "0" ];then rm -rf run_03remove_TR.sh.done;fi
if [ ! -e run_03remove_TR.sh.done ];then echo -e "Clean up tandem repeat failed" && exit 1;fi
cat stat.txt
mkdir -p $wkdir/output_of_EDTA-RepeatModeler2;
cp genome.RM2.raw.fa genome.RM2.all.fa genome.RM2.without_LINE_SINE.fa genome.LINE.raw.fa genome.LINE_SINE.raw.fa genome.SINE.raw.fa $wkdir/output_of_EDTA-RepeatModeler2/
cat stat.txt|sed 's# * #\t#g' >$wkdir/output_of_EDTA-RepeatModeler2/RepeatModeler2.stat.xls
echo -e "\n\033[01;35m#######Results#######\033[0m"
echo "Output: $wkdir/output_of_EDTA-RepeatModeler2"
if [ `cat $wkdir/zg-EDTA-RepeatModeler2.err|wc -l` != "0" ];then echo -e "Some tasks failed" && exit 1;fi
