#!/bin/bash
genome=`realpath $1`
threads=$2
species=$3
skip_blastn=$4
para_task_num=$5
chunk_size=$6
overlap=50000
bin_dir=`realpath $0|xargs -n1 dirname`
cleanup_tandem=$bin_dir/scripts/software/EDTA-2.2.2/bin/cleanup_tandem.pl
output_by_list=$bin_dir/scripts/software/EDTA-2.2.2/bin/output_by_list.pl
cleanup_misclas=$bin_dir/scripts/software/EDTA-2.2.2/bin/cleanup_misclas.pl
rename_tirlearner=$bin_dir/scripts/software/EDTA-2.2.2/bin/rename_tirlearner.pl
bed2gff=$bin_dir/scripts/software/EDTA-2.2.2/bin/bed2gff.pl
get_ext_seq=$bin_dir/scripts/software/EDTA-2.2.2/bin/get_ext_seq.pl
flank_filter=$bin_dir/scripts/software/EDTA-2.2.2/bin/flanking_filter.pl
wkdir=$PWD
maxint=5000
#maximum interval length (bp) between TIRs (for GRF in TIR-Learner)
echo -e "\033[01;35m#######Data#######\033[0m"
echo -e "Genome: ${genome}
Threads: $threads
Species: $species
Skip Blastn: $skip_blastn
Parallel Task Num: $para_task_num
Split Chunk Size: $chunk_size bp"
chunk_size=`echo $chunk_size|sed 's#,##g'`
echo -e "\n\033[01;35m#######Run#######\033[0m"
mkdir -p tmp_of_EDTA-TIR/01.TIR_Learner;cd tmp_of_EDTA-TIR/01.TIR_Learner
echo "1.1. split genome ..."
if [ ! -e run_01split_fa.sh.done ];then
        echo "ln -sf $genome genome.fa && \\
python $bin_dir/scripts/RepeatAnno/split_genome.py genome.fa -c $chunk_size -o $overlap -d genome_split && touch run_01split_fa.sh.done" >run_01split_fa.sh
        bash run_01split_fa.sh 1>run_01split_fa.sh.log 2>run_01split_fa.sh.err
fi
if [ `cat run_01split_fa.sh.err|wc -l` != "0" ];then rm -rf run_01split_fa.sh.done;fi
if [ ! -e run_01split_fa.sh.done ];then echo -e "split genome failed" && exit 1;fi

echo "1.2. run TIR-Learner ..."
if [ ! -e run_02TIR.sh.done ];then
	echo "cd $PWD" >run_02TIR.sh.cmds
	for i in `ls -v genome_split/`
	do
	this_genome=`realpath genome_split/${i}`
	if [ -e TIR_split/${i}/run_01TIR_Learner.sh.log ];then
		if [ `cat TIR_split/${i}/run_01TIR_Learner.sh.log|grep "No TIR found"|wc -l` != "0" ];then touch TIR_split/${i}/run_01TIR_Learner.sh.done;fi
	fi
	if [ ! -e TIR_split/${i}/run_01TIR_Learner.sh.done ];then
		mkdir -p TIR_split/${i}
		echo "ln -sf ${this_genome} used.genome.fa;mkdir -p output_of_TIR tmp_of_TIR && \\
rm -rf output_of_TIR/* tmp_of_TIR/* && ulimit -n 8192 && \\
TIR-Learner -f \$PWD/used.genome.fa -t $threads -s $species -l $maxint -c -o \$PWD/output_of_TIR --working_dir \$PWD/tmp_of_TIR 
touch run_01TIR_Learner.sh.done" >TIR_split/${i}/run_01TIR_Learner.sh
		echo "cd TIR_split/${i} && bash run_01TIR_Learner.sh 1>run_01TIR_Learner.sh.log 2>run_01TIR_Learner.sh.err && echo finish" >>run_02TIR.sh.cmds
	fi
	done
	task_n=`cat run_02TIR.sh.cmds|sed '1d'|wc -l`
	if [ "$task_n" != "0" ];then
	        echo "Total Task Num: $task_n"
        	echo "parallel -j $para_task_num <run_02TIR.sh.cmds |pv -f -s $task_n -p -l -e -t -b >/dev/null && touch run_02TIR.sh.done" >run_02TIR.sh
	        bash run_02TIR.sh 2> >(tee run_02TIR.sh.log >&1)
	fi
fi
for i in `ls -v TIR_split/`
do
	#if [ `cat TIR_split/${i}/run_01TIR_Learner.sh.err|wc -l` != "0" ];then rm -rf TIR_split/${i}/run_01TIR_Learner.sh.done && rm -rf run_02TIR.sh.done;fi
	if [ `cat TIR_split/${i}/run_01TIR_Learner.sh.log|grep "No TIR found"|wc -l` != "0" ];then touch TIR_split/${i}/run_01TIR_Learner.sh.done;fi
	if [ ! -e TIR_split/${i}/run_01TIR_Learner.sh.done ];then echo "$i TIR-Learner failed" && exit 1;fi
done

echo "1.3. combine all results ..."
if [ ! -e run_03merge.sh.done ];then
	mkdir -p output_of_TIR/TIR-Learner-Result/
	echo "#!/bin/bash
rm -rf output_of_TIR/TIR-Learner-Result/* && \\
for i in \`ls -v TIR_split/\`
do
	if [ -s TIR_split/\$i/output_of_TIR/TIR-Learner-Result/TIR-Learner_FinalAnn.gff3 ];then
		cat TIR_split/\$i/output_of_TIR/TIR-Learner-Result/TIR-Learner_FinalAnn.gff3|sed 's#\\.\\.#\\t#g'|awk '{print \$1\"\\t\"\$4\"\\t\"\$5\"\\t\"\$6+\$2-1\"\\t\"\$7+\$2-1\"\\t\"\$8\"\\t\"\$9\"\\t\"\$10\"\\t\"\$11\"\\t\"\$12}'|sed 's#\\t\$##g' >>output_of_TIR/TIR-Learner-Result/TIR-Learner_FinalAnn.gff3
	fi
done && \\
rm -rf genome.fa.fai && samtools faidx genome.fa && \\
cat output_of_TIR/TIR-Learner-Result/TIR-Learner_FinalAnn.gff3|sed '/^$/d'|while read n
do
	id=\`echo -e \"\$n\"|awk '{print \">TIR-Learner_\"\$1\"_\"\$4\"_\"\$5\"_\"\$3\"_\"\$9}'\`
	region=\`echo -e \"\$n\"|awk '{print \$1\":\"\$4\"-\"\$5}'\`
	cat <(echo -e \"\$id\") <(samtools faidx genome.fa \$region|sed '1d')|seqkit seq -j 30 -w0 >>output_of_TIR/TIR-Learner-Result/TIR-Learner_FinalAnn.fa
done && \\
ln -sf output_of_TIR/TIR-Learner-Result/TIR-Learner_FinalAnn.gff3 ./ && \\
ln -sf output_of_TIR/TIR-Learner-Result/TIR-Learner_FinalAnn.fa ./ && \\
touch run_03merge.sh.done" >run_03merge.sh
	bash run_03merge.sh 1>run_03merge.sh.log 2>run_03merge.sh.err
fi
if [ ! -e run_03merge.sh.done ];then echo "combine all results failed" && exit 1;fi
mkdir -p ../02.deal_with;cd ../02.deal_with
genome=used.genome.fa
blastplus=`command -v makeblastdb 2>/dev/null|xargs -n1 dirname`
echo "2.1. clean raw predictions with flanking alignment ..."
if [ ! -e run_01clean.sh.done ];then
	mkdir -p 01.clean_raw_predict && rm -rf 01.clean_raw_predict/*
	echo "cd 01.clean_raw_predict && ln -sf ../../01.TIR_Learner/genome.fa ./used.genome.fa && \\
perl $rename_tirlearner ../../01.TIR_Learner/output_of_TIR/TIR-Learner-Result/*FinalAnn.fa | perl -nle 's/TIR-Learner_//g; print \$_' >${genome}.TIR && \\
perl $get_ext_seq ${genome} ${genome}.TIR && \\
if [ \"$skip_blastn\" != \"skip_blastn\" ];then
	perl $flank_filter -genome ${genome} -query ${genome}.TIR.ext30.fa -miniden 90 -mincov 0.9 -maxct 5 -t $threads && \\
	perl $output_by_list 1 ${genome}.TIR 1 ${genome}.TIR.ext30.fa.pass.fa -FA -MSU0 -MSU1 > ${genome}.TIR.ext30.fa.pass.fa.ori
fi && \\
if [ ! -s ${genome}.TIR.ext30.fa.pass.fa.ori ];then
	echo 'TIR.ext30.fa.pass.fa.ori is empty, run cmd:
cat used.genome.fa.TIR >${genome}.TIR.ext30.fa.pass.fa.ori'
	cat used.genome.fa.TIR >${genome}.TIR.ext30.fa.pass.fa.ori
fi && \\
touch ../run_01clean.sh.done" >run_01clean.sh
	bash run_01clean.sh 1>run_01clean.sh.log 2>run_01clean.sh.err
fi
#if [ ! -s 01.clean_raw_predict/used.genome.fa.TIR.ext30.fa.pass.fa ];then rm -rf run_01clean.sh.done && echo "TIR.ext30.fa.pass.fa is empty! ";fi
if [ `cat run_01clean.sh.err|wc -l` != "0" ];then rm -rf run_01clean.sh.done;fi
if [ ! -e run_01clean.sh.done ];then echo -e "clean raw predictions with flanking alignment failed" && exit 1;fi

echo "2.2. remove simple repeats ..."
if [ ! -e run_02remove_TR.sh.done ];then
	mkdir -p 02.remove_TR;
	echo "cd 02.remove_TR && \\
mdust ../01.clean_raw_predict/${genome}.TIR.ext30.fa.pass.fa.ori >${genome}.TIR.ext30.fa.pass.fa.dusted && \\
perl $cleanup_tandem -misschar N -nc 50000 -nr 0.9 -minlen 80 -minscore 3000 -trf 1 -cleanN 1 -cleanT 1 -f ${genome}.TIR.ext30.fa.pass.fa.dusted >${genome}.TIR.ext30.fa.pass.fa.dusted.cln && \\
touch ../run_02remove_TR.sh.done" >run_02remove_TR.sh
	bash run_02remove_TR.sh 1>run_02remove_TR.sh.log 2>run_02remove_TR.sh.err
fi
if [ ! -s 02.remove_TR/${genome}.TIR.ext30.fa.pass.fa.dusted.cln ];then echo "TIR.ext30.fa.pass.fa.dusted.cln is empty! " && rm -rf run_02remove_TR.sh.done;fi
if [ `cat run_02remove_TR.sh.err|wc -l` != "0" ];then rm -rf run_02remove_TR.sh.done;fi
if [ ! -e run_02remove_TR.sh.done ];then echo -e "\nremove simple repeats failed" && exit 1;fi

echo "2.3. annotate and remove non-TIR candidates ..."
if [ ! -e run_03annotate.sh.done ];then
	mkdir -p 03.annotate
	echo "cd 03.annotate && ln -sf ../02.remove_TR/used.genome.fa.TIR.ext30.fa.pass.fa.dusted.cln ./ && \\
ln -sf ../../01.TIR_Learner/output_of_TIR/TIR-Learner-Result/*FinalAnn.gff3 TIR-Learner_FinalAnn.gff3 && \\
TEsorter ${genome}.TIR.ext30.fa.pass.fa.dusted.cln --disable-pass2 -p $threads 2>/dev/null && \\
perl $cleanup_misclas ${genome}.TIR.ext30.fa.pass.fa.dusted.cln.rexdb.cls.tsv && \\
ln -sf ${genome}.TIR.ext30.fa.pass.fa.dusted.cln.cln ${genome}.TIR.intact.raw.fa && \\
ln -sf ${genome}.TIR.ext30.fa.pass.fa.dusted.cln.cln.list ${genome}.TIR.intact.raw.fa.anno.list && \\
perl -nle 's/\\-\\+\\-/_Len:/; my (\$chr, \$method, \$supfam, \$s, \$e, \$anno) = (split)[0,1,2,3,4,8]; my \$class='DNA'; \$class='MITE' if \$e-\$s+1 <= 600; my (\$tir, \$iden, \$tsd)=(\$1, \$2/100, \$3) if \$anno=~/TIR:(.*)_([0-9.]+)_TSD:([a-z0-9._]+)_LEN/i; print \"\$chr \$s \$e \$chr:\$s..\$e \$class/\$supfam structural \$iden . . . TSD=\$tsd;TIR=\$tir\"' TIR-Learner_FinalAnn.gff3 | perl $output_by_list 4 - 1 ${genome}.TIR.intact.raw.fa -MSU0 -MSU1 > ${genome}.TIR.intact.raw.bed && \\
perl $bed2gff ${genome}.TIR.intact.raw.bed TIR >${genome}.TIR.intact.raw.gff3 && \\
touch ../run_03annotate.sh.done" >run_03annotate.sh
	bash run_03annotate.sh 1>run_03annotate.sh.log 2>run_03annotate.sh.err
fi
if [ `cat run_03annotate.sh.err|wc -l` != "0" ];then rm -rf run_03annotate.sh.done;fi
if [ ! -e run_03annotate.sh.done ];then echo "annotate and remove non-TIR candidates failed" && exit 1;fi
genome=genome
mkdir -p $wkdir/output_of_EDTA-TIR/
ln -sf 03.annotate/used.genome.fa.TIR.intact.* ./
cp 03.annotate/used.genome.fa.TIR.intact.raw.bed $wkdir/output_of_EDTA-TIR/${genome}.TIR.intact.raw.bed
cp 03.annotate/used.genome.fa.TIR.intact.raw.fa $wkdir/output_of_EDTA-TIR/${genome}.TIR.intact.raw.fa
cp 03.annotate/used.genome.fa.TIR.intact.raw.gff3 $wkdir/output_of_EDTA-TIR/${genome}.TIR.intact.raw.gff3
if [ `cat $wkdir/zg-EDTA-TIR.err|wc -l` != "0" ];then echo "Some task failed" && exit 1;fi
echo -e "\n\033[01;35m#######Results#######\033[0m"
echo "Output: $wkdir/output_of_EDTA-TIR/"

