#!/bin/bash
genome=`realpath $1`
threads=$2
bin_dir=`realpath $0|xargs -n1 dirname`
cleanup_tandem=$bin_dir/scripts/software/EDTA-2.2.2/bin/cleanup_tandem.pl
output_by_list=$bin_dir/scripts/software/EDTA-2.2.2/bin/output_by_list.pl
cleanup_misclas=$bin_dir/scripts/software/EDTA-2.2.2/bin/cleanup_misclas.pl
wkdir=$PWD
echo -e "\033[01;35m#######Data#######\033[0m"
echo -e "Genome: ${genome}
Threads: $threads"
echo -e "\n\033[01;35m#######Run#######\033[0m"
mkdir -p tmp_of_EDTA-SINE;cd tmp_of_EDTA-SINE;now_dir=$PWD
mkdir -p 01.AnnoSINE;cd 01.AnnoSINE
echo "1. run AnnoSINE_v2 ..."
if [ ! -e run_01AnnoSINE.sh.done ];then
	echo "ln -sf ${genome} used.genome.fa && \\
path_dir=\`command -v AnnoSINE_v2 2>/dev/null|xargs -n1 dirname\`
python3 \$path_dir/AnnoSINE_v2 --temp_dir tmp_of_SINE -t $threads -a 2 --num_alignments 50000 -rpm 0 --copy_number 3 --shift 100 -auto 1 3 used.genome.fa ./ && touch run_01AnnoSINE.sh.done" >run_01AnnoSINE.sh
	bash run_01AnnoSINE.sh 1>run_01AnnoSINE.sh.log 2>run_01AnnoSINE.sh.err
fi
if [ ! -s Seed_SINE.fa ];then echo -e "Seed_SINE.fa is empty! ";fi
if [ ! -e run_01AnnoSINE.sh.done ];then echo -e "run AnnoSINE_v2 failed" && exit 1;fi
genome=genome
mkdir -p ../02.filter;cd ../02.filter
if [ -s ../01.AnnoSINE/Seed_SINE.fa ];then
	ln -sf ../01.AnnoSINE/Seed_SINE.fa
	echo "2. filter and reclassify AnnoSINE candidates with TEsorter and make SINE library ..."
	echo "2.1. annotate and remove non-SINE candidates ..."
	if [ ! -e run_01annotate.sh.done ];then
		echo "awk '{gsub(/Unknown/, \"unknown\"); print \$1}' Seed_SINE.fa > ${genome}.AnnoSINE.raw.fa && \\
TEsorter ${genome}.AnnoSINE.raw.fa --disable-pass2 -p $threads 2>/dev/null && \\
if [ ! -e ${genome}.AnnoSINE.raw.fa.rexdb.cls.tsv ];then touch ${genome}.AnnoSINE.raw.fa.rexdb.cls.tsv;fi && \\
perl $cleanup_misclas ${genome}.AnnoSINE.raw.fa.rexdb.cls.tsv && \\
touch run_01annotate.sh.done" >run_01annotate.sh
		bash run_01annotate.sh 1>run_01annotate.sh.log 2>run_01annotate.sh.err
	fi
	if [ `cat run_01annotate.sh.err|wc -l` != "0" ];then rm -rf run_01annotate.sh.done;fi
	if [ ! -e run_01annotate.sh.done ];then echo "annotate and remove non-SINE candidates failed" && exit 1;fi
	echo "2.2. clean up tandem repeat ..."
	if [ ! -e run_02remove_TR.sh.done ];then
		echo "perl $cleanup_tandem -misschar N -nc 50000 -nr 0.8 -minlen 80 -minscore 3000 -trf 1 -cleanN 1 -cleanT 1 -f ${genome}.AnnoSINE.raw.fa.cln > ${genome}.SINE.raw.fa && \\
seqkit seq -n genome.SINE.raw.fa|sort -k1 -V|seqtk subseq Seed_SINE.fa -|sed 's#SINE_[0-9]* ##g'|sed 's%|.*|%#SINE/%g'|sed 's#_rRNA\$##g'|sed 's#_RNA\$##g'|sed 's#Unknown#unknown#g'|sed 's#:#..#g'|sed 's/ /_/g'|awk '/^>/ {\$0 = \$0 \" SINE_\" i++} 1' >genome.SINE.rename.fa && \\
touch run_02remove_TR.sh.done" >run_02remove_TR.sh
		bash run_02remove_TR.sh 1>run_02remove_TR.sh.log 2>run_02remove_TR.sh.err
	fi
	if [ `cat run_02remove_TR.sh.err|wc -l` != "0" ];then rm -rf run_02remove_TR.sh.done;fi
	if [ ! -e run_02remove_TR.sh.done ];then echo "clean up tandem repeat failed" && exit 1;fi
else
       	touch ${genome}.SINE.raw.fa genome.SINE.rename.fa
fi

mkdir -p $wkdir/output_of_EDTA-SINE/
cp ${genome}.SINE.raw.fa genome.SINE.rename.fa $wkdir/output_of_EDTA-SINE/
echo -e "\n\033[01;35m#######Results#######\033[0m"
echo "Output: $wkdir/output_of_EDTA-SINE/"
if [ `cat $wkdir/zg-EDTA-SINE.err|wc -l` != "0" ];then echo "Some tasks failed" && exit 1;fi
